version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - mynetwork
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2
    container_name: redis
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  github-detection:
    build:
      context: ./backend/services/github_detection
      dockerfile: Dockerfile
    container_name: github_detection
    ports:
      - "8003:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - rabbitmq
      - redis
    networks:
      - mynetwork
    secrets:
      - github_env

  github-detection-worker:
    build:
      context: ./backend/services/github_detection
      dockerfile: workers/Dockerfile
    container_name: github_detection_worker
    depends_on:
      - rabbitmq
      - redis
    networks:
      - mynetwork
    secrets:
      - github_env

  # React 프론트엔드 (CORS 해결)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ossguard_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://github-detection:8000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on:
      - github-detection
    networks:
      - mynetwork

secrets:
  github_env:
    file: ./backend/secrets/github_env

networks:
  mynetwork:
    driver: bridge

# version: '3'

# services:
#   rabbitmq:
#     image: rabbitmq:management
#     container_name: rabbitmq
#     environment:
#       - RABBITMQ_DEFAULT_USER=myuser
#       - RABBITMQ_DEFAULT_PASS=mypassword
#     networks:
#       - mynetwork
#     ports:
#       - "5672:5672"
#       - "15672:15672"

#   redis:
#     image: redis:6.2
#     container_name: redis
#     networks:
#       - mynetwork
#     ports:
#       - "6379:6379"

#   github-detection:
#     build:
#       context: ./backend/services/github_detection
#       dockerfile: Dockerfile
#     container_name: github_detection
#     ports:
#       - "8003:8000"
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#     depends_on:
#       - rabbitmq
#       - redis
#     networks:
#       - mynetwork
#     secrets:
#       - github_env

#   github-detection-worker:
#     build:
#       context: ./backend/services/github_detection
#       dockerfile: workers/Dockerfile
#     container_name: github_detection_worker
#     depends_on:
#       - rabbitmq
#       - redis
#     networks:
#       - mynetwork
#     secrets:
#       - github_env

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: ossguard_frontend
#     ports:
#       - "3000:3000"
#     environment:
#       - REACT_APP_API_URL=http://localhost:8003
#       - REACT_APP_API_BASE_URL=http://github-detection:8000
#     depends_on:
#       - github-detection
#     networks:
#       - mynetwork
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules

# secrets:
#   github_env:
#     file: ./backend/secrets/github_env

# networks:
#   mynetwork:
#     driver: bridge